services:
  - type: web
    name: greenreguai
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: http://greenreguai-api:8000/*
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: /api

  - type: web
    name: greenreguai-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: STORAGE_BUCKET
        value: official_documents
